
symbologies = {
    "1": "Code 11",
    "2": "Standard Code 2 of 5",
    "3": "Interleaved 2 of 5",
    "4": "Code 2 of 5 IATA",
    "6": "Code 2 of 5 Data Logic",
    "7": "Code 2 of 5 Industrial",
    "8": "Code 3 of 9 (Code 39)",
    "9": "Extended Code 3 of 9 (Code 39+)",
    "13": "EAN",
    "16": "GS1-128 (UCC.EAN-128)",
    "18": "Codabar",
    "20": "Code 128 (automatic subset switching)",
    "21": "Deutshe Post Leitcode",
    "22": "Deutshe Post Identcode",
    "23": "Code 16K",
    "24": "Code 49",
    "25": "Code 93",
    "28": "Flattermarken",
    "29": "GS1 DataBar-14",
    "30": "GS1 DataBar Limited",
    "31": "GS1 DataBar Extended",
    "32": "Telepen Alpha",
    "34": "UPC A",
    "37": "UPC E",
    "40": "PostNet",
    "47": "MSI Plessey",
    "49": "FIM",
    "50": "LOGMARS",
    "51": "Pharmacode One-Track",
    "52": "PZN",
    "53": "Pharmacode Two-Track",
    "55": "PDF417",
    "56": "PDF417 Truncated",
    "57": "Maxicode",
    "58": "QR Code",
    "60": "Code 128 (Subset B)",
    "63": "Australia Post Standard Customer",
    "66": "Australia Post Reply Paid",
    "67": "Australia Post Routing",
    "68": "Australia Post Redirection",
    "69": "ISBN (EAN-13 with verification stage)",
    "70": "Royal Mail 4 State (RM4SCC)",
    "71": "Data Matrix",
    "72": "EAN-14",
    "75": "NVE-18",
    "76": "Japanese Postal Code",
    "77": "Korea Post",
    "79": "GS1 DataBar-14 Stacked",
    "80": "GS1 DataBar-14 Stacked Omnidirectional",
    "81": "GS1 DataBar Expanded Stacked",
    "82": "PLANET",
    "84": "MicroPDF417",
    "85": "USPS OneCode",
    "86": "Plessey Code",
    "87": "Telepen Numeric",
    "89": "ITF-14",
    "90": "Dutch Post KIX Code",
    "92": "Aztec Code",
    "93": "DAFT Code",
    "97": "Micro QR Code",
    "98": "HIBC Code 128",
    "99": "HIBC Code 39",
    "102": "HIBC Data Matrix",
    "104": "HIBC QR Code",
    "106": "HIBC PDF417",
    "108": "HIBC MicroPDF417",
    "112": "HIBC Aztec Code",
    "128": "Aztec Runes",
    "129": "Code 32",
    "130": "Composite Symbol with EAN linear component",
    "131": "Composite Symbol with GS1-128 linear component",
    "132": "Composite Symbol with GS1 DataBar-14 linear component",
    "133": "Composite Symbol with GS1 DataBar Limited component",
    "134": "Composite Symbol with GS1 DataBar Extended component",
    "135": "Composite Symbol with UPC A linear component",
    "136": "Composite Symbol with UPC E linear component",
    "137": "Composite Symbol with GS1 DataBar-14 Stacked component",
    "138": "Composite Symbol with GS1 DataBar-14 Stacked Omnidirectional component",
    "139": "Composite Symbol with GS1 DataBar Expanded Stacked component",
    "140": "Channel Code",
    "141": "Code One",
    "142": "Grid Matrix",
}
